"""add snapshot table

Revision ID: 22de799cc6b1
Revises: e86383c5ff6c
Create Date: 2022-12-09 08:32:06.139423

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = '22de799cc6b1'
down_revision = 'e86383c5ff6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
