"""tweets

Revision ID: 2ef8236b19e4
Revises: d663013bd4a9
Create Date: 2022-11-12 14:45:44.820446

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = '2ef8236b19e4'
down_revision = 'd663013bd4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
