"""author,category,draft

Revision ID: 40dcd6e454c9
Revises: 2ef8236b19e4
Create Date: 2022-11-16 10:50:13.122815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = '40dcd6e454c9'
down_revision = '2ef8236b19e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articlebase_blurb', table_name='articlebase')
    op.drop_index('ix_articlebase_date', table_name='articlebase')
    op.drop_index('ix_articlebase_is_longform', table_name='articlebase')
    op.drop_index('ix_articlebase_link', table_name='articlebase')
    op.drop_index('ix_articlebase_outlet', table_name='articlebase')
    op.drop_index('ix_articlebase_title', table_name='articlebase')
    op.drop_table('articlebase')
    op.add_column('article', sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('article', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_article_author'), 'article', ['author'], unique=False)
    op.create_index(op.f('ix_article_category'), 'article', ['category'], unique=False)
    op.create_index(op.f('ix_article_is_draft'), 'article', ['is_draft'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_is_draft'), table_name='article')
    op.drop_index(op.f('ix_article_category'), table_name='article')
    op.drop_index(op.f('ix_article_author'), table_name='article')
    op.drop_column('article', 'category')
    op.drop_column('article', 'author')
    op.create_table('articlebase',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('blurb', sa.VARCHAR(), nullable=False),
    sa.Column('link', sa.VARCHAR(), nullable=False),
    sa.Column('outlet', sa.VARCHAR(), nullable=False),
    sa.Column('is_longform', sa.BOOLEAN(), nullable=False),
    sa.Column('date', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articlebase_title', 'articlebase', ['title'], unique=False)
    op.create_index('ix_articlebase_outlet', 'articlebase', ['outlet'], unique=False)
    op.create_index('ix_articlebase_link', 'articlebase', ['link'], unique=False)
    op.create_index('ix_articlebase_is_longform', 'articlebase', ['is_longform'], unique=False)
    op.create_index('ix_articlebase_date', 'articlebase', ['date'], unique=False)
    op.create_index('ix_articlebase_blurb', 'articlebase', ['blurb'], unique=False)
    # ### end Alembic commands ###
