"""drop snapshots, add image to article

Revision ID: 832949eab44d
Revises: 22de799cc6b1
Create Date: 2022-12-16 09:51:38.483416

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added

from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '832949eab44d'
down_revision = '22de799cc6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_date', table_name='snapshot')
    op.drop_index('ix_snapshot_type', table_name='snapshot')
    op.drop_table('snapshot')
    op.add_column('article', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image')
    op.create_table('snapshot',
    sa.Column('ids', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshot_type', 'snapshot', ['type'], unique=False)
    op.create_index('ix_snapshot_date', 'snapshot', ['date'], unique=False)
    # ### end Alembic commands ###
