"""meta

Revision ID: a9192e44905d
Revises: 832949eab44d
Create Date: 2022-12-23 11:25:43.632427

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = 'a9192e44905d'
down_revision = '832949eab44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
