"""podcast episode title

Revision ID: cdbbaae94785
Revises: fbd4e5763d57
Create Date: 2022-11-25 11:20:40.585426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = 'cdbbaae94785'
down_revision = 'fbd4e5763d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('episode_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_podcast_episode_title'), 'podcast', ['episode_title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_episode_title'), table_name='podcast')
    op.drop_column('podcast', 'episode_title')
    # ### end Alembic commands ###
