"""add draft to podcasts

Revision ID: e86383c5ff6c
Revises: cdbbaae94785
Create Date: 2022-12-02 08:16:35.277262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = 'e86383c5ff6c'
down_revision = 'cdbbaae94785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('is_draft', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_podcast_is_draft'), 'podcast', ['is_draft'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_is_draft'), table_name='podcast')
    op.drop_column('podcast', 'is_draft')
    # ### end Alembic commands ###
