"""add deleted article table

Revision ID: fbd4e5763d57
Revises: 40dcd6e454c9
Create Date: 2022-11-25 10:58:13.237177

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = 'fbd4e5763d57'
down_revision = '40dcd6e454c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articledeleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articledeleted_link'), 'articledeleted', ['link'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articledeleted_link'), table_name='articledeleted')
    op.drop_table('articledeleted')
    # ### end Alembic commands ###
