"""nostr notes

Revision ID: fc6785f74398
Revises: a9192e44905d
Create Date: 2022-12-24 15:23:37.473900

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added



# revision identifiers, used by Alembic.
revision = 'fc6785f74398'
down_revision = 'a9192e44905d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nostrnote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_pk', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nostrnote_article_id'), 'nostrnote', ['article_id'], unique=False)
    op.create_index(op.f('ix_nostrnote_author_pk'), 'nostrnote', ['author_pk'], unique=False)
    op.create_index(op.f('ix_nostrnote_note_id'), 'nostrnote', ['note_id'], unique=False)
    op.create_index(op.f('ix_nostrnote_text'), 'nostrnote', ['text'], unique=False)
    op.create_index(op.f('ix_nostrnote_username'), 'nostrnote', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nostrnote_username'), table_name='nostrnote')
    op.drop_index(op.f('ix_nostrnote_text'), table_name='nostrnote')
    op.drop_index(op.f('ix_nostrnote_note_id'), table_name='nostrnote')
    op.drop_index(op.f('ix_nostrnote_author_pk'), table_name='nostrnote')
    op.drop_index(op.f('ix_nostrnote_article_id'), table_name='nostrnote')
    op.drop_table('nostrnote')
    # ### end Alembic commands ###
